// <auto-generated />
using System;
using EducationProject.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EducationProject.Migrations
{
    [DbContext(typeof(EducationprojectContext))]
    [Migration("20230303154741_title")]
    partial class title
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EducationProject.Models.TbAssignment", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("StudentID");

                    b.Property<int>("MatrialId")
                        .HasColumnType("int")
                        .HasColumnName("MatrialID");

                    b.Property<bool>("Done")
                        .HasColumnType("bit");

                    b.Property<int?>("LevelId")
                        .HasColumnType("int");

                    b.HasKey("StudentId", "MatrialId");

                    b.HasIndex("LevelId");

                    b.HasIndex("MatrialId");

                    b.ToTable("TbAssignment");
                });

            modelBuilder.Entity("EducationProject.Models.TbCode", b =>
                {
                    b.Property<int>("CodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CodeID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodeId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("LevelId")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("StudentID");

                    b.HasKey("CodeId");

                    b.HasIndex("LevelId");

                    b.HasIndex("StudentId");

                    b.ToTable("TbCodes");
                });

            modelBuilder.Entity("EducationProject.Models.TbLevel", b =>
                {
                    b.Property<int>("LevelId")
                        .HasColumnType("int");

                    b.Property<string>("YearLevel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("LevelId");

                    b.ToTable("TbLevel");
                });

            modelBuilder.Entity("EducationProject.Models.TbMatrial", b =>
                {
                    b.Property<int>("MatrialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MatrialID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MatrialId"));

                    b.Property<int?>("LevelId")
                        .HasColumnType("int");

                    b.Property<string>("MatrialName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("MatrialId");

                    b.HasIndex("LevelId");

                    b.ToTable("TbMatrial");
                });

            modelBuilder.Entity("EducationProject.Models.TbStudent", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("StudentID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<int?>("LevelId")
                        .HasColumnType("int");

                    b.Property<string>("StudentFullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("StudentId");

                    b.HasIndex("LevelId");

                    b.ToTable("TbStudent");
                });

            modelBuilder.Entity("EducationProject.Models.TbTeacher", b =>
                {
                    b.Property<int>("TeacherId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TeacherID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeacherId"));

                    b.Property<string>("TeacherName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("TeacherId");

                    b.ToTable("TbTeacher");
                });

            modelBuilder.Entity("EducationProject.Models.TbVideo", b =>
                {
                    b.Property<int>("VideoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("VideoID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VideoId"));

                    b.Property<int?>("LevelId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("URL");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VideoId");

                    b.HasIndex("LevelId");

                    b.ToTable("TbVideos");
                });

            modelBuilder.Entity("MatrialVideo", b =>
                {
                    b.Property<int>("MatrialId")
                        .HasColumnType("int")
                        .HasColumnName("MatrialID");

                    b.Property<int>("VideoId")
                        .HasColumnType("int")
                        .HasColumnName("VideoID");

                    b.HasKey("MatrialId", "VideoId");

                    b.HasIndex("VideoId");

                    b.ToTable("MatrialVideo", (string)null);
                });

            modelBuilder.Entity("StudentMatrial", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("StudentID");

                    b.Property<int>("MatrialId")
                        .HasColumnType("int")
                        .HasColumnName("MatrialID");

                    b.HasKey("StudentId", "MatrialId");

                    b.HasIndex("MatrialId");

                    b.ToTable("StudentMatrial", (string)null);
                });

            modelBuilder.Entity("TbMatrialTbStudent", b =>
                {
                    b.Property<int>("MatrialId")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("MatrialId", "StudentId");

                    b.ToTable("TbMatrialTbStudent");
                });

            modelBuilder.Entity("TbMatrialTbTeacher", b =>
                {
                    b.Property<int>("MatrialId")
                        .HasColumnType("int");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.HasKey("MatrialId", "TeacherId");

                    b.ToTable("TbMatrialTbTeacher");
                });

            modelBuilder.Entity("TbMatrialTbVideo", b =>
                {
                    b.Property<int>("MatrialId")
                        .HasColumnType("int");

                    b.Property<int>("VideoId")
                        .HasColumnType("int");

                    b.HasKey("MatrialId", "VideoId");

                    b.ToTable("TbMatrialTbVideo");
                });

            modelBuilder.Entity("TbMatrialTeacher", b =>
                {
                    b.Property<int>("MatrialId")
                        .HasColumnType("int")
                        .HasColumnName("MatrialID");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int")
                        .HasColumnName("TeacherID");

                    b.HasKey("MatrialId", "TeacherId");

                    b.HasIndex("TeacherId");

                    b.ToTable("TbMatrialTeacher", (string)null);
                });

            modelBuilder.Entity("EducationProject.Models.TbAssignment", b =>
                {
                    b.HasOne("EducationProject.Models.TbLevel", "Level")
                        .WithMany("TbAssignments")
                        .HasForeignKey("LevelId")
                        .HasConstraintName("FK_TbAssignment_TbLevel");

                    b.HasOne("EducationProject.Models.TbMatrial", "Matrial")
                        .WithMany("TbAssignments")
                        .HasForeignKey("MatrialId")
                        .IsRequired()
                        .HasConstraintName("FK_TbAssignment_TbMatrial");

                    b.HasOne("EducationProject.Models.TbStudent", "Student")
                        .WithMany("TbAssignments")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FK_TbAssignment_TbStudent");

                    b.Navigation("Level");

                    b.Navigation("Matrial");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("EducationProject.Models.TbCode", b =>
                {
                    b.HasOne("EducationProject.Models.TbLevel", "Level")
                        .WithMany("TbCodes")
                        .HasForeignKey("LevelId")
                        .HasConstraintName("FK_TbCodes_TbLevel");

                    b.HasOne("EducationProject.Models.TbStudent", "Student")
                        .WithMany("TbCodes")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FK_TbCodes_TbStudent");

                    b.Navigation("Level");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("EducationProject.Models.TbMatrial", b =>
                {
                    b.HasOne("EducationProject.Models.TbLevel", "Level")
                        .WithMany("TbMatrials")
                        .HasForeignKey("LevelId")
                        .HasConstraintName("FK_TbMatrial_TbLevel");

                    b.Navigation("Level");
                });

            modelBuilder.Entity("EducationProject.Models.TbStudent", b =>
                {
                    b.HasOne("EducationProject.Models.TbLevel", "Level")
                        .WithMany("TbStudents")
                        .HasForeignKey("LevelId")
                        .HasConstraintName("FK_TbStudent_TbLevel");

                    b.Navigation("Level");
                });

            modelBuilder.Entity("EducationProject.Models.TbVideo", b =>
                {
                    b.HasOne("EducationProject.Models.TbLevel", "Level")
                        .WithMany("TbVideos")
                        .HasForeignKey("LevelId")
                        .HasConstraintName("FK_TbVideos_TbLevel");

                    b.Navigation("Level");
                });

            modelBuilder.Entity("MatrialVideo", b =>
                {
                    b.HasOne("EducationProject.Models.TbMatrial", null)
                        .WithMany()
                        .HasForeignKey("MatrialId")
                        .IsRequired()
                        .HasConstraintName("FK_MatrialVideo_TbMatrial");

                    b.HasOne("EducationProject.Models.TbVideo", null)
                        .WithMany()
                        .HasForeignKey("VideoId")
                        .IsRequired()
                        .HasConstraintName("FK_MatrialVideo_TbVideos");
                });

            modelBuilder.Entity("StudentMatrial", b =>
                {
                    b.HasOne("EducationProject.Models.TbMatrial", null)
                        .WithMany()
                        .HasForeignKey("MatrialId")
                        .IsRequired()
                        .HasConstraintName("FK_StudentMatrial_TbMatrial");

                    b.HasOne("EducationProject.Models.TbStudent", null)
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FK_StudentMatrial_TbStudent");
                });

            modelBuilder.Entity("TbMatrialTeacher", b =>
                {
                    b.HasOne("EducationProject.Models.TbMatrial", null)
                        .WithMany()
                        .HasForeignKey("MatrialId")
                        .IsRequired()
                        .HasConstraintName("FK_TbMatrialTeacher_TbMatrial");

                    b.HasOne("EducationProject.Models.TbTeacher", null)
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .IsRequired()
                        .HasConstraintName("FK_TbMatrialTeacher_TbTeacher");
                });

            modelBuilder.Entity("EducationProject.Models.TbLevel", b =>
                {
                    b.Navigation("TbAssignments");

                    b.Navigation("TbCodes");

                    b.Navigation("TbMatrials");

                    b.Navigation("TbStudents");

                    b.Navigation("TbVideos");
                });

            modelBuilder.Entity("EducationProject.Models.TbMatrial", b =>
                {
                    b.Navigation("TbAssignments");
                });

            modelBuilder.Entity("EducationProject.Models.TbStudent", b =>
                {
                    b.Navigation("TbAssignments");

                    b.Navigation("TbCodes");
                });
#pragma warning restore 612, 618
        }
    }
}
